name: portfolio
description: Portfolio Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Widgets
  flutter_advanced_drawer: ^1.3.5
  flutter_svg: ^2.0.1
  marqueer: ^1.4.0
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0+1
  flutter_html: ^3.0.0-beta.2
  flutter_tilt: ^2.2.1
  syncfusion_flutter_charts: ^24.2.6
  scrollable_positioned_list: ^0.3.8

  # Core
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  url_launcher: ^6.1.4
  page_transition: ^2.0.5
  resize: ^1.0.0
  intl: ^0.18.1
  gap: ^3.0.1
  http: ^1.2.1
  oktoast: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: space_grotesk
      fonts:
        - asset: assets/fonts/sg300.ttf
          weight: 300
        - asset: assets/fonts/sg400.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/sg500.ttf
          weight: 500
        - asset: assets/fonts/sg600.ttf
          weight: 600
        - asset: assets/fonts/sg700.ttf
          weight: 700

  assets:
    - assets/
    - assets/anim/
    - assets/fonts/
    - assets/images/
    - assets/logo/