name: portfolio
description: Portfolio Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.1
  lottie: ^2.3.2
  url_launcher: ^6.1.4
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  get: ^4.6.1
  page_transition: ^2.0.5
  resize: ^1.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0

flutter:

  uses-material-design: true

  fonts:
    - family: noto
      fonts:
        - asset: assets/fonts/light.ttf
          weight: 300
        - asset: assets/fonts/regular.ttf
          style: normal
        - asset: assets/fonts/medium.ttf
          weight: 500
        - asset: assets/fonts/semi_bold.ttf
          weight: 600
        - asset: assets/fonts/bold.ttf
          weight: 700
        - asset: assets/fonts/extra_bold.ttf
          weight: 800

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/anim/