name: portfolio
description: Portfolio Project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Widgets
  flutter_advanced_drawer: ^1.3.5
  flutter_svg: ^2.0.1
  lottie: ^2.3.2
  marqueer: ^1.4.0
  auto_size_text: ^3.0.0
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0+1

  # Core
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  url_launcher: ^6.1.4
  page_transition: ^2.0.5
  resize: ^1.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto.ttf

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/anim/
    - assets/logo/