name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - '.github/workflows/**'
      - 'pubspec.yaml'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Flutter Setup
        uses: subosito/flutter-action@v2.13.0
        with:
          channel: 'stable'
          cache: true

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        env:
          WEB_ENV: ${{ secrets.WEB_ENV_VAR }}
        run: |
          echo "$WEB_ENV"
          echo "$WEB_ENV" > prod.json 
          flutter build web --web-renderer canvaskit --release --dart-define-from-file=prod.json

      - name: Create Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web/
          retention-days: 1

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Git Setup
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git config --global user.email yashashm.dev@gmail.com
          git config --global user.name yashas-hm
          git clone https://$ACCESS_TOKEN@github.com/yashas-hm/yashas-hm.github.io.git

      - name: Get Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: flutter-web-build
          path: build/

      - name: Push to Server Branch
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          # Copy Build
          echo pwd
          cp -rf build/ .
          # Deploy
          git add .
          git commit -m "Workflow Deploy"
          git push